### PR TITLE
Add dotnet 7 image

### PR DESCRIPTION
**Pull request by RyanCallahan312**
Adding a dotnet 7 image would be super helpful to me and I'm sure others that have looked at #11. I'm not sure what the contributing guidelines are but hopefully, this is enough to get the ball rolling. Please do let me know if this doesn't meet the requirements as I am unclear on what exactly loft-sh/setup-devspace or other github actions might be doing to add everything to the image.

### CODE REVIEW

**Comment by carlmontanari** [comment]
hey @RyanCallahan312, thanks for this!

looks cool on a quick glance, one question is: in .net land do you always just use latest .net version? reason for asking is do we want to have 6.x and 7.x in the pipeline or just 7.x? for example in the go workflow we have a few major versions [here](https://github.com/loft-sh/devspace-containers/blob/main/.github/workflows/go.yaml#L27-L31), do we want to have that option here as well?

**Comment by RyanCallahan312** [comment]
@carlmontanari That makes complete sense to me. I added the versions that are still in official support (see [here](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)) as well as dotnet 5 because it was a major milestone when it was released and hasn't been out of support for too long.

Thanks for pointing that out!

**Comment by carlmontanari** [comment]
thanks @RyanCallahan312 lgtm, will get it merged and make sure the builds are looking happy :)

**Comment by carlmontanari** [comment]
quick update, looks like im going to yoink the 5.0 tag out -- there isn't an arm image for that one it seems. so if folks need .net 5.0 things they can just build that one for themselves!

**Pull request merged**
